services:
  - type: web
    name: czcash-pcs-fork-fe
    runtime: node
    plan: starter
    buildCommand: pnpm install && pnpm build
    startCommand: pnpm start
    envVars:
      - key: NODE_VERSION
        value: 20.18.0
      - key: PNPM_VERSION
        value: 8.15.9
      - key: NODE_ENV
        value: production
